package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Monday, May 11, 2026 10:30:13 AM PDT
*/

public interface ReverseOperations 
{
  String reverse_string (String name);
} // interface ReverseOperations
